apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: train-schedule
  name: train-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-schedule
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: train-schedule
    spec:
      containers:
      - image: prasadcm/train-schedule
        name: train-schedule
        resources: {}
status: {}
